[package]
name = "bevy_3d_sprite"
version = "0.1.0"
edition = "2021"

[dependencies.bevy]
version = "0.10.1"
default-features = false
features = [
    "bevy_asset",
    "bevy_pbr",
    "bevy_sprite",
    "png"
]

[dependencies.image]
version = "0.24.6"
default-features = false
features = ["png"]